[project]
name = "GIC_Cinema"
version = "0.1.0"
authors = [{ name="Ow Yong Gui Kang", email="gui_kang@hotmail.com" }]
description = "GIC Cinemas Booking System"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]